version: '3.7'


services:
  selenium:
    image: selenium/standalone-chrome:4.1.3-20220405
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: 2g
    restart: always

  client:
    build: 
      context: '.'
    container_name: client
    volumes:
      - './src:/src/'
    depends_on:
      - selenium

    
  # dummy:
  #   image: 'ubuntu'
  #   depends_on:
  #     - client
      
  # tcpdump_client:
  #   build: '../tcpdump'
  #   command: not(ip6) -v -w "/data/dump-client-${CAPTURETIME}-$REPNUM.pcap"
  #   volumes:
  #     - './data:/data'
  #   network_mode: "service:client"
  #   depends_on:
  #     - dummy
      
