version: '3.7'

services:
  wireguard-client:
    image: linuxserver/wireguard
    container_name: wireguard-client
    restart: unless-stopped
    networks:
      backbone:
        ipv4_address: 172.16.236.44
    volumes:
      - './client/wireguard-config:/config/'
      - '/lib/modules:/lib/modules:ro'
    environment:
      - PUID=1000
      - PGID=1000
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 4444:4444
      - 4445:4445
      - 4446:4446
      - 7900:7900
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0

  browser:
    image: selenium/standalone-${BROWSER}:4.1.3-20220405
    container_name: browser
    shm_size: 2g
    restart: always
    network_mode: service:wireguard-client

  client:
    depends_on:
      - wireguard-client
      - browser
    build: './client'
    container_name: client
    volumes:
      - './client/src:/src/'
    environment:
      REPEAT: ${REPEAT}
      URL: ${URL}
      BROWSER: ${BROWSER}
      MODE: ${MODE}
    network_mode: service:wireguard-client

  dummy:
    image: 'ubuntu'
    networks:
      - backbone
    depends_on:
      - client
      
  tcpdump_client:
    build: './tcpdump'
    command: not(ip6) -v -w "/data/user-${BROWSER}-${MODE}-${URL}.pcap"
    volumes:
      - './data:/data'
    network_mode: "service:client"
    depends_on:
      - dummy
      
  eve:
    build: './tcpdump'
    container_name: eve
    network_mode: "host" ## only way to sniff traffic on same host is by listening to Linux bridge of Host (I shit you not, there was one guy who asked it on three sites and wrote the reply himself after)
    cap_add:
      - NET_RAW
      - NET_ADMIN
    ports:
      - 51820:51820
    privileged: true
    command: host 172.16.236.44 -i any -v -w "/data/eve-${BROWSER}-${MODE}-${URL}.pcap"
    volumes:
      - './data:/data'
    depends_on:
      - dummy

networks:
  backbone:
    driver: bridge
    ipam:
          driver: default
          config:
          - subnet: 172.16.236.0/24
