version: "2.1"
services:
  client:
    build: .
    container_name: client
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      capture:
        ipv4_address: 172.16.236.38
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      
networks:
  capture:
    driver: "bridge"
    ipam:
      driver: default
      config:
      - subnet: 172.16.236.0/28
        gateway: 172.16.236.5

